name: Changelogger

on:
  push:
    branches:
      - main

jobs:
  changelogger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install dependencies
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install axios dotenv

      - name: Create changelog
        run: |
          git log -1 --pretty=format:"%h - %s (%an, %ar)" > changelog.txt
          node ./server.js
