name: Changelogger

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Changelogger
        run: node action/changelogger.js
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FLASK_API_URL: "http://localhost:8000/generate" 
