name: Changelogger

on:
  push:
    branches:
      - main

jobs:
  changelogger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Extract commit messages
        id: commits
        run: |
          COMMITS=$(git log -1 --pretty=format:"%s%n%b")
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug commit messages
        run: |
          echo "Commit messages: ${{ steps.commits.outputs.commits }}"

      - name: Send commits to backend
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
        run: |
          COMMITS="${{ steps.commits.outputs.commits }}"
          jq -n --arg msg "$COMMITS" '{commits: [{ message: $msg }]}' | \
          curl -X POST $BACKEND_URL -H "Content-Type: application/json" \
               -H "Authorization: Bearer $GEMINI_API_KEY" -d @-
