name: Changelogger

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Gather commit data and generate changelog
        run: |
          python -c "
          import json
          import subprocess
          import requests

          commit_data = subprocess.check_output(['git', 'log', '--pretty=format:%H%n%an%n%at%n%s%n%b%n==END==', '--reverse']).decode('utf-8')
          commits = [dict(zip(['hash', 'author', 'timestamp', 'subject', 'body'], c.split('\n'))) for c in commit_data.split('==END==\n') if c.strip()]

          prompt = 'Generate a changelog based on the following commits:\n\n'
          for commit in commits:
              prompt += f'- {commit['subject']} (by {commit['author']})\n'

          response = requests.post('https://log-tab7.onrender.com/generate', json={'prompt': prompt})
          generated_changelog = response.json()['generated_text']

          with open('CHANGELOG.md', 'w') as f:
              f.write(generated_changelog)
          "

      - name: Create Pull Request
        env:
          REPO_TOKEN: ${{secrets.REPO_TOKEN}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-changelog
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push origin update-changelog
          gh pr create --title "Update Changelog" --body "Automatically generated changelog update" --base main --head update-changelog